### ISSUE TITLE
Not working on 1.4

### ISSUE THREAD

**Issue by maeishoj** [AngularClass/ng-fx#102]
Hey everyone,

I have ngFx working on a project running angularjs 1.2.

However I just added it to a new project of mine, running 1.4, and is not working! 

I just imported ngFx and TweenMax and then added animations to an element, but nothing gets triggered. no animation shown, but no error thrown either.

Can someone please help me out?

**Comment by nhduc296** [comment]
I have same problem

**Comment by maeishoj** [comment]
I am not sure why i closed this, as it doesn't work.. Is anyone able to help?

**Comment by jasonshark** [comment]
There were some changes to angular animation in 1.4 (http://angularjs.blogspot.com/search/label/announcements). Does your app work when using 1.2 or 1.3?

**Comment by mhartington** [comment]
Getting some errors as well. 

```
Uncaught ReferenceError: TweenMax is not defined
```

Using angular 1.4

**Comment by jasonshark** [comment]
you have to include an additional dependency, also in #83. Be careful cause it there's also a license requirement for a dependency (http://greensock.com/licensing/)

**Comment by Hendrixer** [comment]
sorry for the delay! I'm releasing ngFx v2 tonight, all will be solved!!

**Comment by Hendrixer** [comment]
check out the latest version
