### ISSUE TITLE
transitions 'enter' *before* 'exit.

### ISSUE THREAD

**Issue by finetype** [AngularClass/ng-fx#103]
This could be just me, but for some reason my dynamic transitions do the 'enter' transition _before_ the 'exit' transition, meaning that the new page gets concatenated to the bottom of the current page, before the current page animates out and the newly 'entered' contents snap into place.

What should happen is the old content should fade out before new content fades in.

This is on ngView, btw.
![screencapture](https://cloud.githubusercontent.com/assets/6391152/9916856/32963ecc-5c84-11e5-9e4e-9efe4517f71d.gif)

Not really sure how or where to begin troubleshooting that. Seems like it should be obvious or small, but also seems (to me) like that's somewhere inside of angular and/or this plugin, not something I'm able to tweak as a standard user.

**Comment by Hendrixer** [comment]
this is a css issue, you need to make the 'pages' absolutely positioned when animating. Because they are block, they stack up. sorry for the delay! I'm releasing ngFx v2 tonight, all will be solved!!

**Comment by jitendersandhu** [comment]
Hi Hendrixer, any idea when fix for the above issue will be released. Thanks in advance!
