### ISSUE TITLE
Install problem with agular1.4.5

### ISSUE THREAD

**Issue by pooyadg** [AngularClass/ng-fx#104]
When I want to install ngFx for my project with angular 1.4, I face the following output:

**$ bower install ngFx --save**
>bower ngFx#*                    cached git://github.com/Hendrixer/ngFx.git#1.1.0
>bower ngFx#*                  validate 1.1.0 against git://github.com/Hendrixer/ngFx.git#*
>bower angular#~1.3.0            cached git://github.com/angular/bower-angular.git#1.3.19
>bower angular#~1.3.0          validate 1.3.19 against git://github.com/angular/bower-angular.git#~1.3.0
>bower gsap#~1.11.6              cached git://github.com/greensock/GreenSock-JS.git#1.11.8
>bower gsap#~1.11.6            validate 1.11.8 against git://github.com/greensock/GreenSock->JS.git#~1.11.6
>bower angular-animate#~1.3.0    cached git://github.com/angular/bower-angular-animate.git#1.3.19
>bower angular-animate#~1.3.0  validate 1.3.19 against git://github.com/angular/bower-angular-animate.git#~1.3.0
>bower angular#1.4.5             cached git://github.com/angular/bower-angular.git#1.4.5
>bower angular#1.4.5           validate 1.4.5 against git://github.com/angular/bower-angular.git#1.4.5
>bower                        ECONFLICT Unable to find suitable version for angular

I tried to use `resolutions` to point to `"angular": "~1.3.x"`, but nothing happened. Any idea?

**Comment by Mislead** [comment]
+1. Same problem for me

**Comment by Hendrixer** [comment]
sorry for the delay! I'm releasing ngFx v2 tonight, all will be solved!!

**Comment by Hendrixer** [comment]
check out the latest version
