### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by mcneela86** [AngularClass/ng-fx#107]
I have followed the instructions to install with npm 'npm i ngFx --save' I have also tried 'npm install ngFx --save'. But neither way is working for me.

Has this been updated/renamed?

**Comment by Witcher42** [comment]
I have the same problem.

**Comment by Hendrixer** [comment]
sorry for the delay! I'm releasing ngFx v2 tonight, all will be solved!!

**Comment by mcneela86** [comment]
I just ran 'npm i --save ng-fx' which worked. next I added:
    require('angular-animate');
    require('ng-fx');

When I run my gulp build task to open my local server I get the following error:
    Error: module "ng-fx" not found from "path/to/project/angular-gulp-browserify/app/scripts/fake_51af8c2d.js"

I then opened the 'package.json' file for ng-fx and changed the main file from ' "main": "dist/ngFx.js" ' to ' "main": "dist/ng-fx.js" ' and then get a different error:
    Error: module "!!./../../../node_modules/css-loader/index.js!./../../../node_modules/stylus-loader/index.js!./view.styl" not found from "path/to/project/angular-gulp-browserify/node_modules/ng-fx/dist/ng-fx.js"

Not sure if I am doing something wrong? I am using browserify for my angular app.

**Comment by Hendrixer** [comment]
that change to the main file should've did it. I did accidentally push up a version recently that did not have the dist files in the package. Try deleting and installing again @mcneela86 . I just updated and tested it.

**Comment by mcneela86** [comment]
Hey @Hendrixer I have given that a try but I still get:
```
Error: module "!!./../../../node_modules/css-loader/index.js!./../../../node_modules/stylus-loader/index.js!./view.styl" not found from "path/to/project/angular-gulp-browserify/node_modules/ng-fx/dist/ng-fx.js"
```

This is the dependencies from my package.json:
```
"dependencies": {
    "angular": "^1.4.7",
    "angular-animate": "^1.4.7",
    "angular-ui-router": "^0.2.15",
    "jquery": "^2.1.4",
    "ng-fx": "^2.0.4"
  }
```

I can add this to a GitHub repo if you want to have a look?

**Comment by cyrixmorten** [comment]
Same problem here, any updates on the issue?

**Comment by mackelito** [comment]
Installing with bower results in "ngFx": "~1.1.0"... is v2 not available on bower?

**Comment by francesco-carrella** [comment]
Same issue here. Any solution at this? Is there some other unspecified dependency?

**Comment by realph** [comment]
Same problem here.

**Comment by fmtoffolo** [comment]
Same problem here. Any fix?

**Comment by fredybawa** [comment]
I comment the code bellow from the file **ng-fx.js** on the **dist** directory and it worked fined.

Don't know what this code are actually does but somehow it was causing this error.

```javascript
if(!content.locals) {
  module.hot.accept("!!./../../../../node_modules/css-loader/index.js!./../../../../node_modules/stylus-loader/index.js!./rotate.styl", function() {
	var newContent = require("!!./../../../../node_modules/css-loader/index.js!./../../../../node_modules/stylus-loader/index.js!./rotate.styl");
	if(typeof newContent === 'string') newContent = [[module.id, newContent, '']];
	    update(newContent);
  });
}
```

**Comment by demelvin** [comment]
Same issue

**Comment by ademilhan041** [comment]
Same issue
