### ISSUE TITLE
Error Chorme 46, angular 1.3.15

### ISSUE THREAD

**Issue by aronrodrigues** [AngularClass/ng-fx#108]
Unexpected token import on app.js:1

**Comment by aronrodrigues** [comment]
Can I use it as a CDN?
<script src="//cdn.rawgit.com/AngularClass/ng-fx/master/src/app.js"></script>

**Comment by Hendrixer** [comment]
what version of ng-fx are you using? >=v2.0 must use angular 1.4

**Comment by aronrodrigues** [comment]
It was 1.3.15. Will upgrade to 1.4.7 tonight.  What is the cdn for version 2?

**Comment by Hendrixer** [comment]
Its not on a cdn yet :(
