### ISSUE TITLE
bower install

### ISSUE THREAD

**Issue by brandom** [AngularClass/ng-fx#109]
It appears that v2 is not available on bower.

**Comment by scfbarbat** [comment]
+1

**Comment by atd** [comment]
We also manage our angular dependencies with bower, so a bower package would be convenient

Thank you for this awesome library!

**Comment by mgoku** [comment]
+1

**Comment by jonathanwoahn** [comment]
Just wanted to let you know that the install via NPM is not the same package available on this website. NPM points to https://registry.npmjs.org/ng-fx/-/ng-fx-2.0.4.tgz. I was able to get this working in bower by pointing to this registry, but it definitely is not optimal.

This library is awesome though - thanks for doing it. I've never created a package on bower, so I'm not sure what's involved in making that happen, but this would definitely be super convenient to have it registered there.

**Comment by mackelito** [comment]
Would also like to use bower.. our gulp config depends on it :+1:

**Comment by s2ugimot** [comment]
+1

I've made a branch for bower installation. Here's a temporally solution:
`bower install --save s2ugimot/ng-fx#2.0.5-bower`

**Comment by jojoyuji** [comment]
+1 thx @s2ugimot

**Comment by chidg** [comment]
@s2ugimot's command didn't work for me, however `bower install https://github.com/s2ugimot/ng-fx.git#2.0.5-bower --save` did.

**Comment by caglarcem** [comment]
+1
