### ISSUE TITLE
The example on the repo page is not running as expected

### ISSUE THREAD

**Issue by adamchenwei** [AngularClass/ng-fx#80]
I used the exact code offered in the example, however, the 2nd exmaple's

<h1 go-away class='fx-zoom-up'> This will zoom out when the fade animation is done</h1>

part will just suddenly vanish after the trigger, there is no fx- ### effect applied to the h1 content.

I wonder did anywhere I got wrong in term of using libraries?

Thanks

I am using:

<script src="/library/angularjs/1.3.0/angular.js"></script>

```
<script src="/library/angularjs/1.3.0/angular-route.js"></script>
<script src="/library/angularjs/1.3.0/angular-animate.js"></script>
<script src="/library/angular-ui/ng-router/0.2.13/js/angular-ui-router.js"></script>
<script src="/library/angular-ui/bootstrap/0.12.0/js/ui-bootstrap-tpls.js"></script>
<script src="/library/angularjs/directives/fx/1.11.8/js/ngFx.js"></script>
```

**Comment by Hendrixer** [comment]
I think the readme is outdated, let me check, thanks

**Comment by adamchenwei** [comment]
Thanks! Specifically its about the directive that was made is not really working.

app.directive('goAway', function($animate){
  function link(scope, element){
    scope.$on('fade-down:enter', function(){
    	console.log("WOOOOOOO")
      $animate.leave(element);
    });
  }
  return {
    restrict: 'A',
    link: link
  };
});

**Comment by adamchenwei** [comment]
Again, very very very cool lib! Just want to get this working :)

Thanks!

**Comment by mmodi** [comment]
rtyry

**Comment by Hendrixer** [comment]
Working on this today
