### ISSUE TITLE
Translate(x,y) Animation

### ISSUE THREAD

**Issue by ahetawal-p** [AngularClass/ng-fx#84]
Looking for a some help here. Of all the animation libraries I have looked at, not able to find one which provides an easy translate(x,y) animation. Are there are any plans to add it, will really make this library a complete one. 
Something like this  http://jsfiddle.net/doktormolle/adcvK/
Thanks for the amazing work on this till now.

**Comment by Hendrixer** [comment]
I like that. Right now I'm making the library more modular so creating new animations would be trivial.
