### ISSUE TITLE
transition conflicts with bootstrap carousel 

### ISSUE THREAD

**Issue by nvcken** [AngularClass/ng-fx#85]
if angular.module include ngFx then bootstrap carousel  prev() next() not work.
When not include , it 's work
code from bootstrap carousel  next button click

``` javascript
$scope.next = function() {
    var newIndex = (currentIndex + 1) % slides.length;

    //Prevent this user-triggered transition from occurring if there is already one in progress
    if (!$scope.$currentTransition) {
      return self.select(slides[newIndex], 'next');
    }
  };
```

when debug I see !$scope.$currentTransition return false so it not run into "return self.select(slides[newIndex], 'next');"

**Comment by Hendrixer** [comment]
I'll look into it, any errors in the console?

**Comment by nvcken** [comment]
Have no any errors output in console.

**Comment by Hendrixer** [comment]
still working on this
