### ISSUE TITLE
White screen on ipad

### ISSUE THREAD

**Issue by lardi** [AngularClass/ng-fx#93]
Hi,
I have followed all the steps:
1- I have created a new app with a sidemenu.
2- I included ngFx.js to my index file.
3- I include ngFx to app.js like this

```
angular.module('starter', ['ionic', 'starter.controllers', 'ngFx', 'ngAnimate'])
```

when I type (iconic serve) it's work perfectly, but when I run it on ios devices I get a white screen.

my ionic version is 1.3.18

**Comment by Hendrixer** [comment]
is there an error?

**Comment by lardi** [comment]
When I check logs in Chrome I found nothing there same as in Xcode, Just white screen.
