### ISSUE TITLE
Ng-switch - wait for animation to finish before beginning the next one

### ISSUE THREAD

**Issue by reinman** [AngularClass/ng-fx#96]
Hey Hendrixer/contributors,

Stumbled upon ngFx after trying to reinvent the wheel with custom GSAP animations - thank you, thank you for making it possible for me to not go down that path.

I'd like to use ngFx on this cool directive I just built:

 <div class="" ng-switch on="login.currentStep">

```
  <!-- First Step in Login Process -->
  <div class="login-body fx-zoom-left fx-easing-back fx-speed-500" ng-switch-when="1">
    <first-step-text></first-step-text>
    <big-input value="login.inputVal" placeholder="Mobile Phone"></big-input>
  </div>

  <!-- Second Step in Login Process -->
  <div staggered class="login-body fx-zoom-right fx-easing-back fx-speed-1000" ng-switch-when="2">
    <second-step-text phone="login.phone"></second-step-text>
    <big-input value="login.inputVal" placeholder="Pin Code"></big-input>
  </div>
</div>
```

I want my second step in the login process to animate in after the first step has finished animating... fx-trigger doesn't seem to fit this use case because as far as I can tell, it's meant for triggering custom animations outside ng-switch, ng-repeat, ng-whatever. 

Right now I'm hacking it by setting the speed of the second step to be greater than the first... is there a better way?

Thank you kindly,
Jordan

**Comment by jitendersandhu** [comment]
+1

**Comment by ruisebastiao** [comment]
+1

**Comment by horst80** [comment]
+1

A workaround (if not a nice one) would be to use an ng-show instead, and use a timeout X (of the same length as fx-speed-X) to activate step 2 after step 1 has been deactivated.
