### ISSUE TITLE
Error: $injector:unpr Unknown Provider  with Angular 1.3.15

### ISSUE THREAD

**Issue by hurstcr** [AngularClass/ng-fx#97]
Getting the following error with angular 1.3.15 and angular-animate 1.3.15  

Unknown provider: $$qProvider <- $$q <- $animate <- $compile

**Comment by wagedomain** [comment]
I was getting a similar error on 1.3.15 - said that ngFx module could not be found.

Updating angular and dependencies to 1.3.16 resolved the issue.

**Comment by vinchi777** [comment]
getting this error for angular and angular-animate 1.5.8
