### ISSUE TITLE
Certain animations flicker on Google Chrome

### ISSUE THREAD

**Issue by abyss-outpost** [AngularClass/ng-fx#99]
1. bounce-left
2. bounce-down
3. fade-down
4. bounce-up
5. zoom-up
6. bounce-right
7. bounce-normal

These flicker on animation entry, but not on animation exit.

**Comment by Hendrixer** [comment]
sorry for the delay! I'm releasing ngFx v2 tonight, all will be solved!!

**Comment by Hendrixer** [comment]
download the latest version
